[package]
name = "rust-haskell"
version = "0.1.0"
authors = ["Matthew Harm Bekkema <mbekkema97@gmail.com>"]
build = "build.rs"

[lib]
name = "haskell"

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3"
