[package]
name = "HSfoo"
version = "0.1.0"
authors = ["Matthew Harm Bekkema <mbekkema97@gmail.com>"]
build = "build.rs"

[lib]
name = "foo"

[dependencies]
rust-haskell = { path = "../haskell" }
libc = "0.2"

[build-dependencies]
gcc = "0.3"
